export const queryKeys = {
  prayersToday: (params) => ["prayers", "today", params],
  prayersMonth: (params) => ["prayers", "month", params],
  methods: ["prayers", "methods"],
  cities: (q) => ["cities", q],
  daily: ["daily"],
  surahs: (lang) => ["quran", "surahs", lang],
  surah: (id, opts) => ["quran", "surah", id, opts],
  juz: ["quran", "juz"],
  reciters: ["quran", "reciters"],
  tafsirs: ["quran", "tafsirs"],
  duas: (category) => ["duas", category],
  dua: (id) => ["dua", id],
  hadithCollections: ["hadith", "collections"],
  hadithList: (id, page) => ["hadith", id, page],
  hadith: (id, n) => ["hadith", id, n],
  names: (q) => ["names", q],
  prayerLog: (date) => ["prayer-log", date],
  stats: ["stats"],
  fasting: ["fasting"],
  qibla: (lat, lng) => ["qibla", lat, lng],
  calendar: ["calendar"],
  me: ["me"],
};
